import utils from '../osg/utils.js';
import Animation from '../osgAnimation/animation.js';
import SkinningAttribute from '../osgAnimation/SkinningAttribute.js';
import AnimationUpdateCallback from '../osgAnimation/AnimationUpdateCallback.js';
import BasicAnimationManager from '../osgAnimation/BasicAnimationManager.js';
import Bone from '../osgAnimation/Bone.js';
import Channel from '../osgAnimation/channel.js';
import CollectAnimationUpdateCallbackVisitor from '../osgAnimation/CollectAnimationUpdateCallbackVisitor.js';
import Easing from '../osgAnimation/easing.js';
import Interpolator from '../osgAnimation/interpolator.js';
import MorphAttribute from '../osgAnimation/MorphAttribute.js';
import MorphGeometry from '../osgAnimation/MorphGeometry.js';
import RigGeometry from '../osgAnimation/RigGeometry.js';
import Skeleton from '../osgAnimation/Skeleton.js';
import StackedMatrix from '../osgAnimation/StackedMatrix.js';
import StackedQuaternion from '../osgAnimation/StackedQuaternion.js';
import StackedRotateAxis from '../osgAnimation/StackedRotateAxis.js';
import StackedScale from '../osgAnimation/StackedScale.js';
import StackedTranslate from '../osgAnimation/StackedTranslate.js';
import UpdateBone from '../osgAnimation/UpdateBone.js';
import UpdateMatrixTransform from '../osgAnimation/UpdateMatrixTransform.js';
import UpdateMorph from '../osgAnimation/UpdateMorph.js';
import UpdateSkeleton from '../osgAnimation/UpdateSkeleton.js';

var osgAnimation = {};

utils.objectMix(osgAnimation, Easing);
utils.objectMix(osgAnimation, Interpolator);
osgAnimation.Animation = Animation;
osgAnimation.SkinningAttribute = SkinningAttribute;
osgAnimation.AnimationUpdateCallback = AnimationUpdateCallback;
osgAnimation.BasicAnimationManager = BasicAnimationManager;
osgAnimation.Bone = Bone;
osgAnimation.Channel = Channel;
osgAnimation.CollectAnimationUpdateCallbackVisitor = CollectAnimationUpdateCallbackVisitor;
osgAnimation.MorphAttribute = MorphAttribute;
osgAnimation.MorphGeometry = MorphGeometry;
osgAnimation.RigGeometry = RigGeometry;
osgAnimation.Skeleton = Skeleton;
osgAnimation.StackedMatrix = StackedMatrix;
osgAnimation.StackedQuaternion = StackedQuaternion;
osgAnimation.StackedRotateAxis = StackedRotateAxis;
osgAnimation.StackedScale = StackedScale;
osgAnimation.StackedTranslate = StackedTranslate;
osgAnimation.UpdateBone = UpdateBone;
osgAnimation.UpdateMatrixTransform = UpdateMatrixTransform;
osgAnimation.UpdateMorph = UpdateMorph;
osgAnimation.UpdateSkeleton = UpdateSkeleton;

export default osgAnimation;
