import AutoTransform from '../osg/AutoTransform.js';
import BillboardAttribute from '../osg/BillboardAttribute.js';
import BlendColor from '../osg/BlendColor.js';
import BlendFunc from '../osg/BlendFunc.js';
import BoundingBox from '../osg/BoundingBox.js';
import BoundingSphere from '../osg/BoundingSphere.js';
import BufferArray from '../osg/BufferArray.js';
import BufferArrayProxy from '../osg/BufferArrayProxy.js';
import Camera from '../osg/Camera.js';
import ColorMask from '../osg/ColorMask.js';
import ComputeBoundsVisitor from '../osg/ComputeBoundsVisitor.js';
import ComputeMatrixFromNodePath from '../osg/computeMatrixFromNodePath.js';
import CullFace from '../osg/CullFace.js';
import CullingSet from '../osg/CullingSet.js';
import CullSettings from '../osg/CullSettings.js';
import CullStack from '../osg/CullStack.js';
import CullVisitor from '../osg/CullVisitor.js';
import Depth from '../osg/Depth.js';
import DrawArrayLengths from '../osg/DrawArrayLengths.js';
import DrawArrays from '../osg/DrawArrays.js';
import DrawElements from '../osg/DrawElements.js';
import EllipsoidModel from '../osg/EllipsoidModel.js';
import FrameBufferObject from '../osg/FrameBufferObject.js';
import FrameStamp from '../osg/FrameStamp.js';
import Geometry from '../osg/Geometry.js';
import { glm } from '../osg/glMatrix.js';
import GLObject from '../osg/GLObject.js';
import Image from '../osg/Image.js';
import ImageStream from '../osg/ImageStream.js';
import KdTree from '../osg/KdTree.js';
import KdTreeBuilder from '../osg/KdTreeBuilder.js';
import Light from '../osg/Light.js';
import LightSource from '../osg/LightSource.js';
import LineWidth from '../osg/LineWidth.js';
import Lod from '../osg/Lod.js';
import Material from '../osg/Material.js';
import osgjsMath from '../osg/math.js';
import MatrixTransform from '../osg/MatrixTransform.js';
import PooledResource from '../osg/PooledResource.js';
import PooledArray from '../osg/PooledArray.js';
import PooledMap from '../osg/PooledMap.js';
import Node from '../osg/Node.js';
import NodeVisitor from '../osg/NodeVisitor.js';
import notify from '../osg/notify.js';
import Object from '../osg/Object.js';
import Options from '../osg/Options.js';
import PagedLOD from '../osg/PagedLOD.js';
import Polytope from '../osg/Polytope.js';
import PointSizeAttribute from '../osg/PointSizeAttribute.js';
import Plane from '../osg/Plane.js';
import primitiveFunctor from '../osg/primitiveFunctor.js';
import primitiveIndexFunctor from '../osg/primitiveIndexFunctor.js';
import primitiveSet from '../osg/primitiveSet.js';
import Program from '../osg/Program.js';
import Projection from '../osg/Projection.js';
import RenderBin from '../osg/RenderBin.js';
import RenderLeaf from '../osg/RenderLeaf.js';
import RenderStage from '../osg/RenderStage.js';
import Shader from '../osg/Shader.js';
import Shape from '../osg/shape.js';
import StackObjectPairPool from '../osg/StackObjectPairPool.js';
import State from '../osg/State.js';
import StateAttribute from '../osg/StateAttribute.js';
import StateGraph from '../osg/StateGraph.js';
import StateSet from '../osg/StateSet.js';
import Switch from '../osg/Switch.js';
import Texture from '../osg/Texture.js';
import TextureCubeMap from '../osg/TextureCubeMap.js';
import Transform from '../osg/Transform.js';
import TriangleIndexFunctor from '../osg/TriangleIndexFunctor.js';
import Uniform from '../osg/Uniform.js';
import UpdateVisitor from '../osg/UpdateVisitor.js';
import utils from '../osg/utils.js';
import Viewport from '../osg/Viewport.js';
import Scissor from '../osg/Scissor.js';
import TransformEnums from '../osg/transformEnums.js';
import Timer from '../osg/Timer.js';
import TimerGPU from '../osg/TimerGPU.js';
import VertexArrayObject from '../osg/VertexArrayObject.js';
import WebGLCaps from '../osg/WebGLCaps.js';

var osg = {};
osg.AutoTransform = AutoTransform;
osg.BillboardAttribute = BillboardAttribute;
osg.BlendColor = BlendColor;
osg.BlendFunc = BlendFunc;
osg.BoundingBox = BoundingBox;
osg.BoundingSphere = BoundingSphere;
osg.BufferArray = BufferArray;
osg.BufferArrayProxy = BufferArrayProxy;
osg.ColorMask = ColorMask;
osg.Camera = Camera;
osg.ColorMask = ColorMask;
osg.ComputeBoundsVisitor = ComputeBoundsVisitor;
utils.objectMix(osg, ComputeMatrixFromNodePath);
osg.CullFace = CullFace;
osg.CullingSet = CullingSet;
osg.CullSettings = CullSettings;
osg.CullStack = CullStack;
osg.CullVisitor = CullVisitor;
osg.Depth = Depth;
osg.DrawArrayLengths = DrawArrayLengths;
osg.DrawArrays = DrawArrays;
osg.DrawElements = DrawElements;
osg.EllipsoidModel = EllipsoidModel;
osg.WGS_84_RADIUS_EQUATOR = EllipsoidModel.WGS_84_RADIUS_EQUATOR;
osg.WGS_84_RADIUS_POLAR = EllipsoidModel.WGS_84_RADIUS_POLAR;
osg.FrameBufferObject = FrameBufferObject;
osg.FrameStamp = FrameStamp;
osg.Geometry = Geometry;
osg.GLObject = GLObject;
osg.Image = Image;
osg.ImageStream = ImageStream;
osg.KdTree = KdTree;
osg.KdTreeBuilder = KdTreeBuilder;
osg.Light = Light;
osg.LightSource = LightSource;
osg.LineWidth = LineWidth;
osg.Lod = Lod;
osg.Material = Material;
utils.objectMix(osg, osgjsMath);
osg.MatrixTransform = MatrixTransform;
osg.PooledResource = PooledResource;
osg.PooledArray = PooledArray;
osg.PooledMap = PooledMap;
osg.Node = Node;
osg.NodeVisitor = NodeVisitor;
utils.objectMix(osg, notify);
osg.Object = Object;
osg.Options = Options;
osg.PagedLOD = PagedLOD;
osg.Plane = Plane;
osg.PointSizeAttribute = PointSizeAttribute;
osg.Polytope = Polytope;
osg.primitiveSet = primitiveSet;
osg.primitiveFunctor = primitiveFunctor;
osg.primitiveIndexFunctor = primitiveIndexFunctor;
osg.Program = Program;
osg.Projection = Projection;
osg.RenderBin = RenderBin;
osg.RenderLeaf = RenderLeaf;
osg.RenderStage = RenderStage;
osg.Shader = Shader;
utils.objectMix(osg, Shape);
osg.StackObjectPairPool = StackObjectPairPool;
osg.State = State;
osg.StateAttribute = StateAttribute;
osg.StateGraph = StateGraph;
osg.StateSet = StateSet;
osg.Scissor = Scissor;
osg.Switch = Switch;
osg.Texture = Texture;
osg.TextureCubeMap = TextureCubeMap;
osg.Transform = Transform;
osg.TriangleIndexFunctor = TriangleIndexFunctor;
osg.Uniform = Uniform;
osg.UpdateVisitor = UpdateVisitor;
utils.objectMix(osg, utils);
osg.Viewport = Viewport;
osg.VertexArrayObject = VertexArrayObject;
osg.vec2 = glm.vec2;
osg.vec3 = glm.vec3;
osg.vec4 = glm.vec4;
osg.quat = glm.quat;
osg.mat3 = glm.mat3;
osg.mat4 = glm.mat4;

osg.Transform.RELATIVE_RF = TransformEnums.RELATIVE_RF;
osg.Transform.ABSOLUTE_RF = TransformEnums.ABSOLUTE_RF;
osg.Timer = Timer;
osg.TimerGPU = TimerGPU;
osg.WebGLCaps = WebGLCaps;

export default osg;
